<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<BuildVersion>1.1.0</BuildVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>CleanCodeAnalyzer</PackageId>
    <PackageVersion>$(BuildVersion)</PackageVersion>
    <Authors>Si Carter</Authors>
    <PackageLicenseUrl>https://github.com/k3ldar/CleanCodeAnalyzer?tab=GPL-3.0-1-ov-file#readme</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/k3ldar/CleanCodeAnalyzer</PackageProjectUrl>
    <RepositoryUrl>https://github.com/k3ldar/CleanCodeAnalyzer</RepositoryUrl>
    <Description>A C# code analyzer enforcing clarity-driven style rules to reduce cognitive load and boost maintainability.</Description>
    <PackageReleaseNotes>Initial release includes 10 analyzers</PackageReleaseNotes>
    <Copyright>Copyright 2025 - Si Carter. All Rights Reserved</Copyright>
    <PackageTags>CleanCodeAnalyzer, analyzers, clean code analyzer</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoPackageAnalysis>true</NoPackageAnalysis>

    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>

    <Title>Clean Code Analyzer</Title>

    <PackageReadmeFile>README.md</PackageReadmeFile>

    <RepositoryType>git</RepositoryType>

    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>

    <EnableNETAnalyzers>True</EnableNETAnalyzers>

    <AnalysisLevel>latest</AnalysisLevel>

    <AssemblyVersion>$(BuildVersion).0</AssemblyVersion>

    <FileVersion>$(BuildVersion).0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanCodeAnalyzer.CodeFixes\CleanCodeAnalyzer.CodeFixes.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\CleanCodeAnalyzer\CleanCodeAnalyzer.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tools\*.ps1" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\CleanCodeAnalyzer.dll" PackagePath="analyzers/dotnet/cs" />
      <TfmSpecificPackageFile Include="$(OutputPath)\CleanCodeAnalyzer.CodeFixes.dll" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
